book:
    resource: "@BookBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
