# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.security.login_form_authenticator:
        class: UserBundle\Security\LoginFormAuthenticator
        autowire: true
