# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.security.login_form_authenticator:
        class: UserBundle\Security\LoginFormAuthenticator
        autowire: true

    user.doctrine.hash_password_listener:
        class: UserBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    book.services.model.bookmanager:
        class: BookBundle\Services\Model\BookManager
        autowire: true
