security:
    providers:
        our_users:
            entity: { class: UserBundle\Entity\User, property: email }

    firewalls:
        main:
            guard:
                authenticators:
                    - user.security.login_form_authenticator

            logout:
                path: /logout
